### ISSUE TITLE
Your GEO script would cause syntax errors

### ISSUE THREAD

**Issue by Razpudding** [TuriGuilano/WAFS#8]
`var position = {
    var POSITION_UPDATED = 'POSITION_UPDATED',
    var REFRESH_RATE = 1000,
    var currentPosition = false,
    var currentPositionMarker = false
}`
Try to run this code in a standalone environment, try to figure out why it doesn't work.

**Comment by TuriGuilano** [comment]
Denk dat je geen vars kan declaren op die manier in een object.. zou ziets zijn van position_updated: 'position_updated', refresh_rate: 1000, currentPosition: false, currentPositionMarker: false  

??

**Comment by Razpudding** [comment]
Klopt! Binnen een object gebruik je het patroon
{
  key0: value,
  key1: value
}
