### ISSUE TITLE
Waar is de liveversie van je SPA?

### ISSUE THREAD

**Issue by Razpudding** [TuriGuilano/WAFS#9]

**Comment by TuriGuilano** [comment]
Excuus, bij deze:

http://oege.ie.hva.nl/~kapriti001/opdracht-5-spa/

**Comment by Razpudding** [comment]
Prachtig die verhalen op je blog! Maarreh, waar is de bron? Ook dit is plagiaat ben ik bang.

**Comment by TuriGuilano** [comment]
Man, mooi over het hoofd gezien, is per direct aangepast. Thanks
